[colors.bright]
black = "#767676"
blue = "#3b78ff"
cyan = "#61d6d6"
green = "#16c60c"
magenta = "#b4009e"
red = "#e74856"
white = "#f2f2f2"
yellow = "#f9f1a5"

[colors.normal]
black = "#0c0c0c"
blue = "#0037da"
cyan = "#3a96dd"
green = "#13a10e"
magenta = "#881798"
red = "#c50f1f"
white = "#cccccc"
yellow = "#c19c00"

[colors.primary]
background = "#0c0c0c"
foreground = "#cccccc"

[font]
size = 13

[font.bold]
family = "terminus"
style = "Bold"

[font.italic]
family = "terminus"
style = "Italic"

[font.normal]
family = "terminus"
style = "Bold"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "NumpadSubtract"
mods = "Control"


[window]
opacity = 0.8
