
[font]
size = 13

[font.bold]
family = "terminus"
style = "Bold"

[font.italic]
family = "terminus"
style = "Italic"

[font.normal]
family = "terminus"
style = "Normal"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "NumpadSubtract"
mods = "Control"


[window]
opacity = 0.8
